### PR TITLE
Drop Aesara support and fix PyTensor compatibility

### PR DESCRIPTION
**Pull request by michaelosthege**
This simplifies testing & upcoming fixes related to changes in shape handling in PyTensor.

### CODE REVIEW

**Comment by michaelosthege** [comment]
@ricardoV94 @aseyboldt the tests here are failing with this:

```
E                           pytensor.graph.utils.MissingInputError: Input 0 (beta) of the graph (indices start from 0), used to compute Shape(beta), was not provided and not given a value. Use the PyTensor flag exception_verbosity='high', for more information on this error.
```

But the shape of `beta` should be trivial, and already known because it's scalar!

```pytensor
beta = pt.dscalar("beta")
```

Am I missing something?

**Comment by michaelosthege** [comment]
Oh, so already this no longer works:

```python
pt.dscalar().shape.eval()
```

But now I'm maximally confused

grafik

**Comment by ricardoV94** [comment]
There's a distinction between `x.shape` and `x.type.shape`. The "static shape" refers to the latter

**Comment by michaelosthege** [comment]
The inspiration for the NumPy minimum version bumps came from https://github.com/conda/conda-build/issues/4498 but it didn't help.

The successful 3.8 jobs were using an old PyTensor version.. Let's see what Python 3.11 brings

**Review by ricardoV94 — APPROVED** [review]

**Comment by maresb** [comment]
Ah, cool! I did that last night and didn't realize it succeeded! 🚀

Unless sunode has some explicit numpy version requirements then it's best to pin implicitly.

**Pull request merged**
